"""empty message

Revision ID: 03ac1501d7cb
Revises: ffa029b484bf
Create Date: 2018-11-06 00:27:50.140757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ac1501d7cb'
down_revision = 'ffa029b484bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'created')
    # ### end Alembic commands ###
