"""empty message

Revision ID: e875f7afe573
Revises: 
Create Date: 2018-11-05 22:49:13.836239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e875f7afe573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registered', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
